config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: %i[create new]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "This movie is already here" }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    before_action :set_list, only: [:new, :create]

    def new
      @bookmark = Bookmark.new
    end

    def create
      @bookmark = Bookmark.new(bookmark_params)
      @bookmark.list = @list
      if @bookmark.save
        redirect_to list_path(@list)
      else
        render :new
      end
    end

    def destroy
      @bookmark = Bookmark.find(params[:id])
      @bookmark.destroy
      redirect_to bookmark_path(@bookmark), status: :see_other
    end

    private


    def bookmark_params
      params.require(:bookmark).permit(:comment, :movie_id, :list_id)
    end

    def set_list
      @list = List.find(params[:list_id])
    end
  end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :movie_id, collection: Movie.all, as: :select, label: "Choose a movie to add" %>
  <%= f.input :comment %>
  <%= f.submit%>
<% end %>

app/views/bookmarks/new.html.erb
<h1>Créer</h1>
<%= render 'form', bookmark: @bookmark %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container d-flex justify-content-center">
      <div class="align-self-center text-center">
        <div class="row col-md-8 mx-auto mt-md-5">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Editer</h1>

app/views/lists/index.html.erb
<div class="container mt-5">
  <div class="text-center mb-4">
    <h1>Watchlist</h1>
    <%= link_to "Ajouter une liste", new_list_path(@bookmark), class: "btn btn-success mt-3" %>
  </div>

  <h2 class="mb-4">Mes listes:</h2>

  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-6 col-lg-4 mb-4">
        <div class="card shadow-sm h-100">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= list.name %></h5>
            <%= link_to "Plus d'informations", list_path(list), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Créer</h1>
<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<div class="container mt-5">
    <h2 class="mb-2">Gestion de la liste</h2>
    <div>
      <%= link_to "Ajouter un Bookmark", new_list_bookmark_path(@list), class: 'btn btn-primary' %>
      <%= link_to "Supprimer un Bookmark", edit_list_path(@list), class: 'btn btn-danger' %>
      <%= link_to "Page d'accueil", lists_path(@list), class: 'btn btn-success' %>
    </div>
  </div>

  <div class="card shadow-sm mt-2">
    <div class="card-body">
      <h3 class="card-title">Films dans la liste</h3>
      <ul class="list-group list-group-flush">
        <% @list.movies.each do |movie| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <span><%= movie.title %></span>
            <span class="badge bg-secondary rounded-pill"><%= movie.rating %></span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>